version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'Test'
      POSTGRES_USERS: 'postgres'
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'